### ISSUE TITLE
Add appropriate error message for advanced error segments

### ISSUE THREAD

**Issue by taapas1128** [taapas1128/Calculator_pyqt#13]
basic errors like 1/0 , log (-ve number) are dealt with . advanced error segments include calculations like log cos(theta)) where cos(theta) is -ve . Hence log(-ve) number cannot be calculated. Find out such error segments and resolve them .

**Comment by taapas1128** [comment]
@07kshitij should I assign it to you ?

**Comment by 07kshitij** [comment]
I'll try to fix it out, but please let others too to look into it, there are a lot of corner cases like 1/(0 + 0) or 1/sin(n*pi) etc. which I might not figure out on my own, so let's keep the issue open to all. Anyone with any inputs may contribute.

**Comment by 07kshitij** [comment]
Done. @taapas1128 Please check

**Comment by 07kshitij** [comment]
> Exactly so this method of classifying each and every error might be quite difficult to work on .Try to go through "error handling in python" you'd may find a solution . Anyway it is open to all.



> Exactly so this method of classifying each and every error might be quite difficult to work on .Try to go through "error handling in python" you'd may find a solution . Anyway it is open to all.

Done. @taapas1128 please check.

**Comment by taapas1128** [comment]
Okay I will check it tonight
