### ISSUE TITLE
add complex mode for complex number addition , substraction , multiplication and calculating argument

### ISSUE THREAD

**Issue by taapas1128** [taapas1128/Calculator_pyqt#5]

**Comment by venkateshdwivedi** [comment]
Complex mode means? making group of new buttons (complex addition button, subtraction button etc.) in the same calculator or something else?

**Comment by venkateshdwivedi** [comment]
![screenshot from 2018-12-10 20-38-46](https://user-images.githubusercontent.com/36000998/49741126-b9239180-fcbb-11e8-9a40-d8e7080741e9.png)
Like this??

**Comment by taapas1128** [comment]
Just you need to the complez number button .. but thats not the only task you need to add the code integration for it too

**Comment by venkateshdwivedi** [comment]
Please review the pr #24

**Comment by taapas1128** [comment]
@venkateshdwivedi this is assigned to you
